### ISSUE TITLE
Consider submitting a minified version to cdnjs

### ISSUE THREAD

**Issue by simevidas** [neovov/Fullscreen-API-Polyfill#13]
It would be useful if a minified version of your polyfill were available on https://cdnjs.com/. If you’ve got time, could you add minification to your Grunt process?

**Comment by neovov** [comment]
cdnjs would only add a library having 100+ stars on GitHub which is, unfortunately, not the case here :).
I added a minification task to the grunt process though.
Thanks :beers: !
