### ISSUE TITLE
webkitFullscreenEnabled

### ISSUE THREAD

**Issue by Aurelain** [neovov/Fullscreen-API-Polyfill#17]
A minor mistake in [line 23](https://github.com/neovov/Fullscreen-API-Polyfill/blob/b193823a5f2b962da8974b539cc6aa796d13ba02/fullscreen-api-polyfill.js#L23).

Should be `webkitFullscreenEnabled` instead of `webkitIsFullScreen`.

**Comment by neovov** [comment]
I think webkit was using `webkitIsFullScreen` before introducing `webkitFullscreenEnabled`.
Thanks for pointing it out :beers:
