### ISSUE TITLE
Current fullscreen element is null in webkitfullscreenchange

### ISSUE THREAD

**Issue by mbixby** [neovov/Fullscreen-API-Polyfill#23]
I was investigating an issue in Safari (9.1.1, OSX 10.11.5) where `document.fullscreenElement` stayed `null` even though `document.webkitFullscreenElement` was correctly set to the fullscreen element.

So I dropped a debugger statement into the `handleChange` (`webkitfullscreenchange`) method and suddenly it worked – `document.fullscreenElement` behaved correctly.

I replaced the debugger statement with console.log and... it broke again. `document.webkitFullscreenElement` was actually **`null`** in `webkitfullscreenchange` handler. When I later poked the property from the console, it was correct.

...This looks like a nice heisenbug unless I'm going crazy. Some screenshots below as proof. I didn't dive in deeper, I think I'll just submit some PR with a hotfix.

<img width="971" alt="screen shot 2016-07-06 at 7 11 28 pm" src="https://cloud.githubusercontent.com/assets/758691/16627684/a2d7cc84-43ae-11e6-857c-b0ebde4dbe38.png">
<img width="717" alt="screen shot 2016-07-06 at 7 11 04 pm" src="https://cloud.githubusercontent.com/assets/758691/16627682/a2b3b56a-43ae-11e6-81c1-9f45567315d9.png">
<img width="1038" alt="screen shot 2016-07-06 at 7 18 30 pm" src="https://cloud.githubusercontent.com/assets/758691/16627683/a2d64170-43ae-11e6-9111-7e6df54e4dfe.png">

**Comment by mbixby** [comment]
Can you actually please add `.editorconfig` before I make any changes? There's something exotic about the source files and Sublime and git diff can't deal with it.

**Comment by neovov** [comment]
Hi @mbixby,

I finally got some time to look at your issue.
I have only Safari 10 and it seems to work correctly (`document.webkitCurrentFullScreenElement` is set in `handleChange`). Would you confirm the issue is still going on in Safari 9 ? Can you try with Safari 10 ?

Thanks, cheers :beers:
