### ISSUE TITLE
Polyfill document.fullScreen

### ISSUE THREAD

**Issue by zdila** [neovov/Fullscreen-API-Polyfill#27]
`document.fullScreen || document.mozFullScreen || document.webkitIsFullScreen`

**Comment by neovov** [comment]
`document.fullscreen` is deprecated since ages. I don't see the point in supporting it.
The spec says to [use `document.fullscreenElement` instead](https://fullscreen.spec.whatwg.org/#dom-document-fullscreen).

**Comment by zdila** [comment]
Thanks for the clarification.
