### ISSUE TITLE
Endless recursion on firefox

### ISSUE THREAD

**Issue by cnspaha** [neovov/Fullscreen-API-Polyfill#29]
When I requestFullscreen via code the polyfill ends in an endless recursion.
Anyone know a way to fix this?
![endlessrecursion](https://cloud.githubusercontent.com/assets/22448974/24450212/5a6026ac-147a-11e7-8f0a-2ca798e8c55a.png)

**Comment by cnspaha** [comment]
was a problem with firefox itself. 
was fixed with v53

**Comment by neovov** [comment]
Cool, thanks for letting me know.
