### ISSUE TITLE
document.fullscreenEnabled not updating in IE 11

### ISSUE THREAD

**Issue by derRaab** [neovov/Fullscreen-API-Polyfill#9]
Thanks for this great polyfill! I just ran into an issue on IE 11, which doesn't update the fullscreenEnabled property correctly. But there is a workaround, simply check for 

var fullscreenEnabled = ( document.fullscreenElement != null );

Just in case you run into the same problem. (I would try to fix it but I'm under extreme project pressure).

**Comment by neovov** [comment]
Hi derRaab,

Thanks for your feedback!
I'll check it out and let you know.

:beers:

**Comment by neovov** [comment]
Hi again derRaab,

I just checked and it seems I cannot reproduce your issue.
With an IE 11.0.9600.17690 I have:

```js
// Not in fullscreen mode:
document.msFullscreenElement; // null
document.fullscreenElement; // null

// In fullscreen mode:
document.msFullscreenElement; // <div>
document.fullscreenElement; // <div>
```

Can you tell me more about your issue?
Thanks.

**Comment by derRaab** [comment]
:) Checking for the fullscreen element works perfect, I was talking about the property:

document.fullscreenEnabled -> which is a boolean (but not updated using your polyfill)

**Comment by neovov** [comment]
Sorry, I was probably too tired to read correctly your issue :smile.
There is a bit of misunderstanding, `document.fullscreenEnabled` doesn't reflect the current fullscreen state (“is my document in fullscreen?”). It reflect the ability to use the API, as stated in the [WHATWG specification](https://fullscreen.spec.whatwg.org/):

> **document.fullscreenEnabled**
> Returns true if document has the ability to display elements fullscreen and fullscreen is supported, or false otherwise.

If you want to know if something is in fullscreen you need to use `document.fullscreenElement`:

```js
var isFullscreen = !!document.fullscreenElement;
```

**Comment by derRaab** [comment]
Sorry - my fault then. :) But I checked if this value is true but it never was. So are you sure you set this to true?

**Comment by neovov** [comment]
Actually this polyfill never set something, it just create some references to the built-in API.
So if `document.msFullscreenEnabled` return `true` ; `document.fullscreenEnabled` will just be a reference to this property. Besides, `fullscreenEnabled` is used to check if the API is available.
